version: "3"
services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    environment:
      EXECUTOR: "Local"
      AIRFLOW_CONN_AIRFLOW_DB: "mysql://user:password@db:3306/chronos"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "mysql://user:password@db:3306/chronos"
  sqs:
    image: "roribio16/alpine-sqs:latest"
    ports:
      - "9324:9324"
      - "9325:9325"
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: "chronos"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
